### PR TITLE
feat: bump yaml and support complex types

### PR DESCRIPTION
**Pull request by costela**
The main work of this PR was actually tracking down where the remaining case mentioned in #6 broke. It turned out that the yaml parser was being overly generic and always parsing into `map[any]any`, when `map[string]any` would suffice.

So bumping yaml to v3 and some minor tweaking of the loader are enough to enable pretty much all the missing use cases. Including the one mentioned in https://github.com/alecthomas/kong/issues/145.

I did some testing on real-world projects and didn't seem to break anything. Did I maybe overlook something?

WDYT?

### CODE REVIEW

**Comment by costela** [comment]
The lint failure seems to be related to hermit using an old version? Not sure.

**Comment by costela** [comment]
@alecthomas friendly ping, just in case this went under the radar :innocent:

**Comment by alecthomas** [comment]
It's not passing lint ^^

**Comment by alecthomas** [comment]
Oh something Hermit related? Lemme check.

**Comment by alecthomas** [comment]
Fixed on master, can you rebase?

**Comment by alecthomas** [comment]
Actually nm I'll just rebase it onto master, should be fine.

**Comment by costela** [comment]
awesome! Thanks for taking the time! :pray:

**Pull request merged**
